# Generated by Django 5.0.8 on 2025-04-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerinfo',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
