# Generated by Django 5.0.8 on 2025-04-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0002_alter_farmerinfo_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerinfo',
            name='dist',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='farmerinfo',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmerinfo',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='farmerinfo',
            name='irrigation',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='farmerinfo',
            name='maincrop',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='farmerinfo',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='farmerinfo',
            name='subdist',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='farmerinfo',
            name='totalland',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmerinfo',
            name='village',
            field=models.CharField(max_length=30),
        ),
    ]
