# Generated by Django 5.0.8 on 2025-04-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0003_alter_farmerinfo_dist_alter_farmerinfo_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('dist', models.CharField(max_length=20)),
                ('subDist', models.CharField(max_length=20)),
                ('village', models.CharField(max_length=30)),
                ('skill', models.CharField(blank=True, max_length=90, null=True)),
                ('availabillity', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
