# Generated by Django 5.0.8 on 2025-04-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0005_worker_mobno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='skill',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
