# Generated by Django 5.0.8 on 2025-04-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0006_alter_worker_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='mobno',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
