# Generated by Django 5.0.8 on 2025-04-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0007_alter_worker_mobno'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='password',
            field=models.CharField(default='worker@123', max_length=20),
            preserve_default=False,
        ),
    ]
