# Generated by Django 5.0.8 on 2025-05-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0010_alter_contactus_email_alter_contactus_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerinfo',
            name='password',
            field=models.CharField(default='Farmer@123', max_length=20),
            preserve_default=False,
        ),
    ]
