# Generated by Django 5.0.8 on 2025-05-10 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0011_farmerinfo_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=200)),
                ('duration', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=200)),
                ('hire_date', models.DateTimeField(auto_now_add=True)),
                ('STATUS', models.CharField(default='pending', max_length=200)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agri.worker')),
            ],
        ),
    ]
