# Generated by Django 5.0.8 on 2025-05-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0012_hirerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirerequest',
            name='mobile_number',
            field=models.CharField(default='123445567895', max_length=10),
            preserve_default=False,
        ),
    ]
