# Generated by Django 5.0.8 on 2025-05-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0013_hirerequest_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hirerequest',
            old_name='mobile_number',
            new_name='f_mobno',
        ),
    ]
