# Generated by Django 5.0.8 on 2025-04-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='password',
            field=models.CharField(default='pass@123', max_length=20),
            preserve_default=False,
        ),
    ]
