# Generated by Django 5.0.8 on 2025-04-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
